name: sintomed_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  flutter_spinkit: ^4.1.2+1
  material_design_icons_flutter: ^4.0.5345
  flare_flutter: ^2.0.4
  flutter_svg: 0.17.4

  # Online
  dio: ^3.0.9

  # Tools
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  provider: ^4.1.3
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
